#include "Skills.h"

Skills::Skills(short* str, short* dex, short* con, short* in, short* wis, short* cha){
	acrobatics = new Skill(dex, false);
	appraise = new Skill(in, false);
	bluff = new Skill(cha, false);
	climb = new Skill(str, false);
	craft = new Skill(in, false);
	diplomacy = new Skill(cha, false);
	disableDevice = new Skill(dex, true);
	disguise = new Skill(cha, false);
	escapeArtist = new Skill(dex, false);
	fly = new Skill(dex, false);
	handleAnimal = new Skill(cha, true);
	heal = new Skill(wis, false);
	intimidate = new Skill(cha, false);
	knowledgeArcana = new Skill(in, true);
	knowledgeDungeoneering = new Skill(in, true);
	knowledgeEngineering = new Skill(in, true);
	knowledgeGeography = new Skill(in, true);
	knowledgeHistory = new Skill(in, true);
	knowledgeLocal = new Skill(in, true);
	knowledgeNature = new Skill(in, true);
	knowledgeNobility = new Skill(in, true);
	knowledgePlanes = new Skill(in, true);
	knowledgeReligion = new Skill(in, true);
	linguistics = new Skill(in, true);
	perception = new Skill(wis, false);
	perform = new Skill(cha, false);
	profession = new Skill(wis, true);
	ride = new Skill(dex, false);
	senseMotive = new Skill(wis, false);
	sleightOfHand = new Skill(dex, true);
	spellcraft = new Skill(in, true);
	stealth = new Skill(dex, false);
	survival = new Skill(wis, false);
	swim = new Skill(str, false);
	useMagicDevice = new Skill(cha, true);
}

void Skills::setClassSkills(ClassName name){
	switch (name){
	case Barbarian: acrobatics->classSkill =
		climb->classSkill =
		craft->classSkill =
		handleAnimal->classSkill =
		intimidate->classSkill =
		knowledgeNature->classSkill =
		perception->classSkill =
		ride->classSkill =
		survival->classSkill =
		swim->classSkill = true; break;
	case Bard: acrobatics->classSkill =
		appraise->classSkill =
		bluff->classSkill =
		climb->classSkill =
		craft->classSkill =
		diplomacy->classSkill =
		disguise->classSkill =
		escapeArtist->classSkill =
		intimidate->classSkill =
		knowledgeArcana->classSkill =
		knowledgeDungeoneering->classSkill =
		knowledgeEngineering->classSkill =
		knowledgeGeography->classSkill =
		knowledgeHistory->classSkill =
		knowledgeLocal->classSkill =
		knowledgeNature->classSkill =
		knowledgeNobility->classSkill =
		knowledgePlanes->classSkill =
		knowledgeReligion->classSkill =
		linguistics->classSkill =
		perception->classSkill =
		perform->classSkill =
		profession->classSkill =
		senseMotive->classSkill =
		sleightOfHand->classSkill =
		spellcraft->classSkill =
		stealth->classSkill =
		useMagicDevice->classSkill = true; break;
	case Cleric: appraise->classSkill =
		diplomacy->classSkill =
		heal->classSkill =
		knowledgeArcana->classSkill =
		knowledgeHistory->classSkill =
		knowledgeNobility->classSkill =
		knowledgePlanes->classSkill =
		knowledgeReligion->classSkill =
		linguistics->classSkill =
		profession->classSkill =
		senseMotive->classSkill =
		spellcraft->classSkill = true; break;
	case Druid: climb->classSkill =
		craft->classSkill =
		fly->classSkill =
		handleAnimal->classSkill =
		heal->classSkill =
		knowledgeGeography->classSkill =
		knowledgeNature->classSkill =
		perception->classSkill =
		profession->classSkill =
		ride->classSkill =
		spellcraft->classSkill =
		survival->classSkill =
		swim->classSkill = true; break;
	case Fighter: climb->classSkill =
		craft->classSkill =
		handleAnimal->classSkill =
		intimidate->classSkill =
		knowledgeDungeoneering->classSkill =
		knowledgeEngineering->classSkill =
		profession->classSkill =
		ride->classSkill =
		survival->classSkill =
		swim->classSkill = true; break;
	case Monk: acrobatics->classSkill =
		climb->classSkill =
		craft->classSkill =
		escapeArtist->classSkill =
		intimidate->classSkill =
		knowledgeHistory->classSkill =
		knowledgeReligion->classSkill =
		perception->classSkill =
		perform->classSkill =
		profession->classSkill =
		ride->classSkill =
		senseMotive->classSkill =
		stealth->classSkill =
		swim->classSkill = true; break;
	case Paladin: craft->classSkill =
		diplomacy->classSkill =
		handleAnimal->classSkill =
		heal->classSkill =
		knowledgeNobility->classSkill =
		knowledgeReligion->classSkill =
		profession->classSkill =
		ride->classSkill =
		senseMotive->classSkill =
		spellcraft->classSkill = true; break;
	case Ranger: climb->classSkill =
		craft->classSkill =
		handleAnimal->classSkill =
		heal->classSkill =
		intimidate->classSkill =
		knowledgeDungeoneering->classSkill =
		knowledgeGeography->classSkill =
		knowledgeNature->classSkill =
		perception->classSkill =
		profession->classSkill =
		ride->classSkill =
		spellcraft->classSkill =
		stealth->classSkill =
		survival->classSkill =
		swim->classSkill = true; break;
	case Rogue: acrobatics->classSkill =
		appraise->classSkill =
		bluff->classSkill =
		climb->classSkill =
		craft->classSkill =
		diplomacy->classSkill =
		disableDevice->classSkill =
		disguise->classSkill =
		escapeArtist->classSkill =
		intimidate->classSkill =
		knowledgeDungeoneering->classSkill =
		knowledgeLocal->classSkill =
		linguistics->classSkill =
		perception->classSkill =
		perform->classSkill =
		profession->classSkill =
		senseMotive->classSkill =
		sleightOfHand->classSkill =
		stealth->classSkill =
		swim->classSkill =
		useMagicDevice->classSkill = true; break;
	case Sorcerer: appraise->classSkill =
		bluff->classSkill =
		craft->classSkill =
		fly->classSkill =
		intimidate->classSkill =
		knowledgeArcana->classSkill =
		profession->classSkill =
		spellcraft->classSkill =
		useMagicDevice->classSkill = true; break;
	case Wizard: appraise->classSkill =
		craft->classSkill =
		fly->classSkill =
		knowledgeArcana->classSkill =
		knowledgeDungeoneering->classSkill =
		knowledgeEngineering->classSkill =
		knowledgeGeography->classSkill =
		knowledgeHistory->classSkill =
		knowledgeLocal->classSkill =
		knowledgeNature->classSkill =
		knowledgeNobility->classSkill =
		knowledgePlanes->classSkill =
		knowledgeReligion->classSkill =
		linguistics->classSkill =
		profession->classSkill =
		spellcraft->classSkill = true; break;
	}
}